import type { Metadata } from "next";
import { Source_Sans_3, Lato } from "next/font/google"; // Import both fonts
import "./globals.css";
import Providers from "@/provider/Provider";
import Script from "next/script";
import Head from "next/head";
 
// Source Sans 3 Font
const sourceSansPro = Source_Sans_3({
  weight: ["300", "400", "600", "700"], // Choose the weights you need
  subsets: ["latin"], // Choose subsets if needed
  display: "swap",
});
 
// Lato Font
const lato = Lato({
  weight: ["300", "400", "700"], // Removed "600" as it is not supported
  subsets: ["latin"], // Choose subsets if needed
  display: "swap",
});
 
export const metadata: Metadata = {
  title: "Trobits",
  description: "Generated by create next app",
};
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en">
<Head>
<script
          type="text/javascript"
          src="https://app.web3ads.net/main.js"
          async
></script>
 
        {/* Newly added script */}
<script
          dangerouslySetInnerHTML={{
            __html: `(function(d,z,s){s.src='https://'+d+'/400/'+z;try{(document.body||document.documentElement).appendChild(s)}catch(e){}})('vemtoutcheeg.com',8865487,document.createElement('script'))`,
          }}
></script>
</Head>
 
      <body
        className={`${sourceSansPro.className} ${lato.className} antialiased`}
>
<Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-101CZRBSL4"
></Script>
 
        <Script id="google-analytics">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
 
            gtag('config', 'G-101CZRBSL4');
          `}
</Script>
 
      
 
        <Providers>{children}</Providers>
</body>
</html>
  );
}
